import Link from "next/link"
import { ArrowRight, Building2, Globe, HouseWifi, Laptop, MapPin, Monitor, ShieldCheck, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Eyebrow } from "./eyebrow"
import { NetworkInstallDiagram } from "./network-install-diagram"
import { NETWORK_CARE_FEATURES } from "@/lib/support-plans"

const SERVICES = [
  { icon: HouseWifi, label: "Home Wi-Fi", title: "Better Wi-Fi in every room.", copy: "Dead zones, slow connections, unreliable mesh, or an overloaded ISP router? Get a network planned around your home.", action: "Improve My Wi-Fi", href: "/home-networking" },
  { icon: Building2, label: "Business Networking", title: "Built around your business.", copy: "Reliable connections for staff, guests, POS systems, cameras, and devices, using professional equipment including Ubiquiti UniFi.", action: "Business Networking", href: "/services" },
  { icon: Laptop, label: "Computer & Tech Help", title: "Something not working? Call us.", copy: "Computers, email, printers, software, accounts, and smart devices. Practical help at your place or remotely.", action: "Get Tech Help", href: "/tech-support" },
]

export function ServicePicker() {
  return <section id="services" className="scroll-mt-24 border-b border-border bg-surface"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24">
    <Eyebrow>Local technology help</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Start with what you need.</h2>
    <div className="mt-10 grid gap-4 md:grid-cols-3">{SERVICES.map(({ icon: Icon, label, title, copy, action, href }) => <article key={href} className="group flex flex-col rounded-2xl border border-border bg-surface-raised p-6 transition-[transform,border-color] duration-300 hover:border-primary/40 motion-safe:hover:-translate-y-1"><Icon aria-hidden="true" className="size-6 text-primary" /><p className="mt-6 font-mono text-xs text-primary">{label}</p><h3 className="mt-3 text-2xl font-semibold tracking-tight">{title}</h3><p className="mt-3 flex-1 text-sm leading-relaxed text-text-secondary">{copy}</p><Link href={href} className="mt-6 inline-flex items-center gap-2 py-2 text-sm font-semibold text-primary hover:underline">{action}<ArrowRight className="size-4" /></Link></article>)}</div>
    <div className="mt-4 flex flex-col gap-5 rounded-2xl border border-border px-6 py-5 sm:flex-row sm:items-center"><Globe aria-hidden="true" className="size-6 shrink-0 text-text-secondary" /><div className="flex-1"><h3 className="font-semibold">Need a better website too?</h3><p className="mt-1 text-sm text-text-secondary">Modern websites for local businesses and restaurants, with hosting and ongoing updates available.</p></div><Link href="/websites" className="inline-flex shrink-0 items-center gap-2 py-2 text-sm font-medium text-primary hover:underline">Website Services <ArrowRight className="size-4" /></Link></div>
  </div></section>
}

const PROBLEMS = [
  { label: "Around your home", href: "/home-networking", items: ["Wi-Fi dead zones", "Slow internet around the house", "UniFi installation", "Router & network upgrades"] },
  { label: "Everyday tech", href: "/tech-support", items: ["New computer setup", "Computer troubleshooting", "Printer problems", "Email & account issues", "Smart TV & device setup", "Remote computer support"] },
  { label: "At your business", href: "/services", items: ["Small-business networks", "Guest Wi-Fi", "POS networking", "Network cleanup"] },
  { label: "On the web", href: "/websites", items: ["Website design", "Website hosting & updates"] },
]

export function CommonProblems() {
  return <section className="border-b border-border"><div className="mx-auto max-w-6xl px-6 py-20"><Eyebrow>Sound familiar?</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">What can we help with?</h2><p className="mt-4 text-text-secondary">You don’t need to know the technical name. Tell us what’s getting in your way.</p><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{PROBLEMS.map((group) => <div key={group.label}><h3 className="border-b border-border pb-3 text-sm font-semibold">{group.label}</h3><ul className="mt-3 space-y-1">{group.items.map((item) => <li key={item}><Link href={group.href} className="inline-flex gap-2 py-2 text-sm text-text-secondary hover:text-primary"><span aria-hidden="true" className="text-primary">↗</span>{item}</Link></li>)}</ul></div>)}</div></div></section>
}

export function NetworkingSpecialty() {
  return <section className="theme-dark band-dark relative overflow-hidden"><div className="pointer-events-none absolute inset-0 bg-topology-glow" /><div className="relative mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-center gap-12 lg:grid-cols-2"><div><Eyebrow>UniFi &amp; networking</Eyebrow><h2 className="mt-4 text-4xl font-bold tracking-tight text-balance sm:text-5xl">Wi-Fi designed around your space.</h2><p className="mt-5 text-lg leading-relaxed text-text-secondary">Walls, rooms, and the devices you use all matter. We evaluate your property, recommend equipment, and plan access-point placement before installing and tuning the network.</p><p className="mt-4 text-text-secondary">Ubiquiti UniFi gateways, switches, and access points are a core specialty. You get a clean installation, tested coverage, and a documented setup you own.</p><Button className="mt-8" render={<Link href="/home-networking" />}>Plan My Wi-Fi <ArrowRight className="size-4" /></Button></div><NetworkInstallDiagram /></div><ul className="mt-12 grid gap-4 border-t border-border pt-8 sm:grid-cols-2 lg:grid-cols-3">{["Whole-home coverage planning", "Wired backhaul where possible", "Proper access-point placement", "Separate guest, IoT & business networks", "Clean, documented installations", "Your hardware. Your accounts."].map((item) => <li key={item} className="flex gap-2 text-sm text-text-secondary"><Check className="size-4 shrink-0 text-primary" />{item}</li>)}</ul></div></section>
}

export function TechSupportSection() {
  return <section className="border-b border-border bg-surface"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid gap-10 lg:grid-cols-2"><div><Eyebrow>On-demand tech support</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight text-balance sm:text-4xl">Have a tech problem? You don’t need an IT department.</h2><p className="mt-5 text-lg leading-relaxed text-text-secondary">A computer acting up. A printer that won’t connect. Email that stopped working. Or a new device you’d like set up properly. Start with the problem, and we’ll figure out the right way to help.</p><Button className="mt-7" render={<Link href="/contact?help=Computer%20%26%20tech%20help" />}>Get Tech Help <ArrowRight className="size-4" /></Button></div><div className="space-y-4">{[{ icon: MapPin, id: "onsite", title: "On-site support", copy: "We come to your home or business in Boca Raton and nearby South Florida communities. Visit availability is confirmed when you get in touch." }, { icon: Monitor, id: "remote", title: "Remote support", copy: "For problems that don’t need a visit, we can securely connect and help remotely, with your permission." }].map(({ icon: Icon, id, title, copy }) => <article id={id} key={id} className="scroll-mt-24 rounded-2xl border border-border bg-surface-raised p-6"><Icon className="size-5 text-primary" /><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-text-secondary">{copy}</p></article>)}</div></div><div className="mt-10 flex items-start gap-3 rounded-xl border border-primary/20 bg-primary/5 p-5"><ShieldCheck aria-hidden="true" className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-relaxed text-text-secondary"><strong className="text-foreground">Remote help starts with you.</strong> ZeroPoint will never unexpectedly call asking to remote into your computer. Sessions only happen after you contact us and authorize the connection.</p></div></div></section>
}

export function NetworkCare({ full = false }: { full?: boolean }) {
  return <section className="border-b border-border"><div className="mx-auto max-w-6xl px-6 py-16"><div className="grid gap-8 rounded-2xl border border-border bg-surface-raised p-6 sm:p-10 lg:grid-cols-2"><div><Eyebrow>Optional after installation</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight">A little ongoing care for your network.</h2><p className="mt-4 leading-relaxed text-text-secondary">Network Care helps keep the setup we’ve installed maintained and documented. Monthly scope, support time, and pricing are agreed around your network.</p><Link href={full ? "/contact?help=Network%20Care" : "/network-care"} className="mt-6 inline-flex items-center gap-2 py-2 font-medium text-primary hover:underline">{full ? "Ask about Network Care" : "Explore Network Care"} <ArrowRight className="size-4" /></Link></div><div><ul className="grid gap-3">{NETWORK_CARE_FEATURES.map((item) => <li key={item} className="flex gap-3 text-sm text-text-secondary"><Check className="size-4 shrink-0 text-primary" />{item}</li>)}</ul><p className="mt-5 border-t border-border pt-4 text-sm text-text-secondary">Support is scoped, with any additional work quoted separately. Monitoring does not include round-the-clock response.</p></div></div></div></section>
}
